recipe: default.v1

assistant_id: 20251024-154957-adaptive-jig

language: zh

pipeline:

  # 中文分词
  - name: JiebaTokenizer
    dictionary_path: "data/dict.txt"
    custom_words_path: "data/dict.txt"
  # 正则特征（支持时间、数字、金额等特征抽取）
  - name: RegexFeaturizer

  # 中文BERT特征（上下文增强）
  - name: LanguageModelFeaturizer
    model_name: "bert"
    model_weights: "./models/bert-base-chinese-tf"
    fine_tune: True

  # 词法/句法特征（捕捉上下文）
  - name: LexicalSyntacticFeaturizer

  # 词级 Bag-of-Words 特征
  - name: CountVectorsFeaturizer
    alias: "cvf-word"

  # 字符级特征（对中文有效）
  - name: CountVectorsFeaturizer
    alias: "cvf-char"
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4

  # 意图 + 实体识别核心
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: True
    entity_recognition: True

  # 同义词映射
  - name: EntitySynonymMapper

  # 回答选择（用于 response）
  - name: ResponseSelector
    epochs: 100

  # # 可选：低置信度兜底
  # - name: FallbackClassifier
  #   threshold: 0.7
  #   ambiguity_threshold: 0.1


policies:

  - name: MemoizationPolicy

  - name: TEDPolicy
    epochs: 100

  - name: RulePolicy
    # enable_fallback_prediction: True



  # - name: UnexpecTEDIntentPolicy
  #   max_history: 5
  #   epochs: 100